# Episode plan data: A1 and A2.
# Each entry: level, person, years, status, title, angle, words ("word|part of speech"), extras, structure, example, topics
def E(level, person, years, status, title, angle, words, extras, structure, example, topics):
    return dict(level=level, person=person, years=years, status=status, title=title, angle=angle,
                words=words, extras=extras, structure=structure, example=example, topics=topics)

A1 = [
    E("A1", "Louis Braille", "1809–1852", "past",
      "He Lost His Sight as a Small Boy… Then Made Letters You Can Feel",
      "At three he hurt his eye with a tool in his father's workshop, and by five he was blind. At fifteen, at a school in Paris, he made a new alphabet of raised dots. Today blind people all over the world read braille.",
      ["dot|noun", "finger|noun", "invent|verb", "letter|noun", "read|verb"], ["tool", "alphabet", "Paris"],
      "was / were (past of be)", "He was only fifteen. The dots were small.", ["Disability", "Invention", "Education"]),
    E("A1", "Hans Christian Andersen", "1805–1875", "past",
      "He Was a Poor Boy… Then Wrote Stories for the Whole World",
      "The son of a poor shoemaker in Denmark, he went to Copenhagen at fourteen with almost no money. He wrote fairy tales like The Ugly Duckling and The Little Mermaid, and children everywhere still read them.",
      ["poor|adjective", "story|noun", "duck|noun", "ugly|adjective", "famous|adjective"], ["fairy tale", "shoemaker", "swan"],
      "there was / there were", "There was a poor boy in Denmark. There were no books in his home.", ["Writing", "Childhood"]),
    E("A1", "Momofuku Ando", "1910–2007", "past",
      "He Was 48 and Had Nothing… Then Invented Instant Noodles",
      "After the war, he saw hungry people waiting in long lines for noodles in Japan. In a small shed behind his house, he tried again and again. In 1958 he made instant noodles, and later Cup Noodles.",
      ["noodles|noun", "hungry|adjective", "cheap|adjective", "cup|noun", "kitchen|noun"], ["shed", "line", "soup"],
      "past simple: regular verbs (-ed)", "He tried and tried. He worked every night.", ["Business", "Food", "Invention"]),
    E("A1", "Jesse Owens", "1913–1980", "past",
      "He Was Poor and Sick as a Boy… Then Won Four Gold Medals",
      "Born in Alabama to a poor family, he was often sick as a child. He ran and jumped at school, and at the 1936 Olympics in Berlin he won four gold medals. A German athlete, Luz Long, became his friend.",
      ["run|verb", "jump|verb", "fast|adjective", "race|noun", "gold|noun"], ["stadium", "athlete", "friend"],
      "past simple: irregular verbs (ran, won, went)", "He ran very fast. He won four races.", ["Sport", "Friendship"]),
    E("A1", "Amelia Earhart", "1897–1937", "past",
      "People Said Women Can't Fly… Then She Crossed the Ocean Alone",
      "She saw her first plane at a fair and did not like it, but her first flight changed everything. In 1932 she flew alone across the Atlantic Ocean, the first woman to do it.",
      ["fly|verb", "plane|noun", "sky|noun", "alone|adjective", "ocean|noun"], ["pilot", "Atlantic", "fair"],
      "the first + noun + to + verb", "She was the first woman to fly across the ocean alone.", ["Aviation", "Women", "Adventure"]),
    E("A1", "Beatrix Potter", "1866–1943", "past",
      "She Wrote a Letter to a Sick Boy… Then Peter Rabbit Was Born",
      "As a lonely girl in London, she drew her pet animals every day. She wrote a picture letter about a rabbit to a sick little boy. It became The Tale of Peter Rabbit. Later she bought farms and gave her land to the nation.",
      ["rabbit|noun", "draw|verb", "farm|noun", "garden|noun", "pet|noun"], ["picture", "lake", "sheep"],
      "love / like + -ing", "She loved drawing animals. She liked walking in the hills.", ["Art", "Nature", "Writing"]),
    E("A1", "Pelé", "1940–2022", "past",
      "He Played With a Ball Made of Socks… Then Won Three World Cups",
      "As a poor boy in Brazil, he could not buy a real ball, so he played with socks full of paper. At seventeen he played in the World Cup and won. He won the World Cup three times.",
      ["ball|noun", "kick|verb", "goal|noun", "team|noun", "sock|noun"], ["Brazil", "cup", "street"],
      "When + past simple", "When he was seventeen, he played in the World Cup.", ["Sport", "Childhood"]),
    E("A1", "Charlie Chaplin", "1889–1977", "past",
      "He Grew Up Poor in London… Then Made the Whole World Laugh",
      "His family had very little money, and his mother was often ill. He went to America and made films. With his little hat, big shoes and walking stick, he became famous — and his films didn't need words.",
      ["funny|adjective", "hat|noun", "laugh|verb", "film|noun", "shoe|noun"], ["walking stick", "actor", "moustache"],
      "past simple negative: didn't + verb", "His films didn't have sound. People didn't need words to laugh.", ["Film", "Comedy"]),
    E("A1", "Walt Disney", "1901–1966", "past",
      "He Drew a Little Mouse… Then Built a Magic Kingdom",
      "He loved drawing as a boy on a farm in Missouri. His first company failed. Then he and his team made a cartoon mouse called Mickey. In 1955 he opened Disneyland.",
      ["mouse|noun", "cartoon|noun", "park|noun", "happy|adjective", "company|noun"], ["drawing", "magic", "studio"],
      "wanted to + verb", "He wanted to make people happy. He wanted to build a park.", ["Film", "Business", "Art"]),
    E("A1", "Neil Armstrong", "1930–2012", "past",
      "He Could Fly Before He Could Drive… Then Walked on the Moon",
      "He loved planes as a boy and had a pilot's licence at sixteen. In 1969 he flew to the Moon on Apollo 11. He stepped onto the Moon and said: \"That's one small step for man…\"",
      ["moon|noun", "rocket|noun", "step|noun", "space|noun", "Earth|noun"], ["flag", "astronaut", "licence"],
      "in / on / at with time (in 1969, on 20 July, at 16)", "In 1969, on 20 July, he walked on the Moon.", ["Space", "Science"]),
    E("A1", "Thomas Edison", "1847–1931", "past",
      "He Went to School for Only a Few Months… Then He Lit Up the World",
      "He went to school for only a few months, and his mother taught him at home. He loved experiments. He and his team tried thousands of materials to make a light bulb that worked for a long time.",
      ["light|noun", "dark|adjective", "try|verb", "bulb|noun", "experiment|noun"], ["lab", "idea", "electric"],
      "again and again / many times", "He tried again and again. He failed many times.", ["Science", "Invention"]),
    E("A1", "Florence Nightingale", "1820–1910", "past",
      "She Walked With a Lamp at Night… Then Changed Hospitals Forever",
      "Her rich family did not want her to be a nurse. In 1854 she went to a war hospital in Turkey. It was dirty. She and her nurses cleaned it and cared for the soldiers. At night she walked with her lamp.",
      ["nurse|noun", "hospital|noun", "clean|verb", "lamp|noun", "soldier|noun"], ["war", "bed", "care"],
      "every day / every night", "Every night, she walked with her lamp.", ["Health", "Women"]),
    E("A1", "Jackie Robinson", "1919–1972", "past",
      "People Shouted at Him… Then He Changed Baseball Forever",
      "In 1947 he became the first Black player in Major League Baseball. Some people shouted at him, but he stayed calm and played very well. Today every player wears his number, 42, on one day each year.",
      ["baseball|noun", "player|noun", "brave|adjective", "number|noun", "shout|verb"], ["fan", "uniform", "calm"],
      "because", "He stayed calm because he wanted to change baseball.", ["Sport", "Equality"]),
    E("A1", "Rosa Parks", "1913–2005", "past",
      "The Driver Told Her to Stand Up… She Said No",
      "In 1955 in Montgomery, Alabama, Black people had to give their bus seats to white people. Rosa Parks was tired of this rule. She did not stand up. Her quiet \"no\" helped change the law.",
      ["bus|noun", "seat|noun", "sit|verb", "driver|noun", "rule|noun"], ["law", "tired", "quiet"],
      "past simple questions: Did…? Yes, she did. / No, she didn't.", "Did she stand up? No, she didn't.", ["Equality", "Courage"]),
    E("A1", "Roald Amundsen", "1872–1928", "past",
      "Five Men, Many Dogs and a Lot of Snow… The First to the South Pole",
      "As a boy in Norway he read about explorers and slept with his window open to get used to the cold. In 1911 he and his team used dogs and skis and reached the South Pole first.",
      ["snow|noun", "ice|noun", "dog|noun", "cold|adjective", "tent|noun"], ["ski", "explorer", "south"],
      "had to + verb", "They had to walk in the snow for many weeks.", ["Adventure", "Exploration"]),
    E("A1", "Mary Anning", "1799–1847", "past",
      "A Poor Girl on the Beach… Then She Found a Sea Monster",
      "She lived by the sea in Lyme Regis, England, and looked for old stones to sell. When she was about twelve, she and her brother found the bones of a huge sea animal. She found many more fossils all her life.",
      ["beach|noun", "stone|noun", "bone|noun", "find|verb", "sea|noun"], ["fossil", "museum", "hammer"],
      "a lot of / many", "She found a lot of bones. Many scientists visited her.", ["Science", "Women", "Nature"]),
    E("A1", "Katsushika Hokusai", "1760–1849", "past",
      "He Painted All His Life… Then Made the Most Famous Wave in the World",
      "He began to paint as a young boy in Japan and never stopped. He moved house many times and changed his name many times. In his seventies he made The Great Wave, a picture people know everywhere.",
      ["wave|noun", "paint|verb", "mountain|noun", "old|adjective", "blue|adjective"], ["boat", "Japan", "print"],
      "very + adjective / really + adjective", "The wave was very big. He was really old, but he painted every day.", ["Art", "Asia"]),
    E("A1", "Albert Einstein", "1879–1955", "past",
      "A Little Compass Made Him Ask Questions… Then He Changed Science",
      "When he was about five, his father showed him a compass. He wanted to know why the needle moved. He asked questions all his life, played the violin, and became one of the most famous scientists in history.",
      ["compass|noun", "question|noun", "ask|verb", "violin|noun", "why|adverb"], ["needle", "science", "math"],
      "wh- questions in the past (Why did…? What did…?)", "Why did the needle move? What did he want to know?", ["Science", "Curiosity"]),
    E("A1", "Jim Henson", "1936–1990", "past",
      "He Made a Frog From His Mother's Old Coat… Then Made the World Smile",
      "In 1955 he made a puppet from his mother's old green coat and a ping-pong ball. The puppet was Kermit the Frog. He made more puppets — the Muppets — and they were on TV all over the world.",
      ["puppet|noun", "frog|noun", "green|adjective", "coat|noun", "TV|noun"], ["ping-pong ball", "show", "voice"],
      "made + noun + from + noun", "He made Kermit from an old coat.", ["TV", "Art", "Comedy"]),
    E("A1", "Milton Hershey", "1857–1945", "past",
      "His First Shops Failed… Then He Built a Chocolate Town",
      "He left school young and worked for a candy maker. His first candy shops failed, but he did not stop. He made money with caramels, then chocolate. He built a town for his workers and a school for children with no parents.",
      ["chocolate|noun", "candy|noun", "sweet|adjective", "factory|noun", "town|noun"], ["caramel", "worker", "shop"],
      "first … then … after that (telling events in order)", "First he made caramels. Then he made chocolate. After that, he built a town.", ["Business", "Food", "Kindness"]),
]

A2 = [
    E("A2", "Marie Curie", "1867–1934", "past",
      "Women Couldn't Go to University… Then She Won Two Nobel Prizes",
      "In Poland, women could not study at university, so she studied in secret and later moved to Paris. She and her husband Pierre discovered two new elements. She won Nobel Prizes in both physics and chemistry.",
      ["prize|noun", "scientist|noun", "discover|verb", "element|noun", "university|noun"], ["physics", "chemistry", "secret school"],
      "both … and", "She won prizes in both physics and chemistry.", ["Science", "Women"]),
    E("A2", "Frida Kahlo", "1907–1954", "past",
      "A Bus Accident Kept Her in Bed… So She Painted Herself",
      "At eighteen she was badly hurt in a bus accident in Mexico. She had to stay in bed for months. Her mother put a mirror above her bed, and Frida began to paint pictures of herself full of colour.",
      ["accident|noun", "mirror|noun", "colourful|adjective", "painting|noun", "hurt|verb"], ["self-portrait", "Mexico", "flower"],
      "past continuous + when (was -ing when…)", "She was riding a bus when the accident happened.", ["Art", "Women", "Courage"]),
    E("A2", "Tenzing Norgay", "1914–1986", "past",
      "He Tried Again and Again… Then Stood on Top of the World",
      "He grew up in the mountains of Nepal and Tibet and carried loads for climbers. He tried to climb Everest many times. In 1953, with Edmund Hillary, he reached the top — the highest place on Earth.",
      ["climb|verb", "top|noun", "rope|noun", "oxygen|noun", "guide|noun"], ["Everest", "Nepal", "camp"],
      "superlatives (the highest, the most dangerous)", "Everest is the highest mountain in the world.", ["Adventure", "Asia"]),
    E("A2", "Jane Goodall", "1934–2025", "past",
      "She Had No University Degree… Then Changed What We Know About Chimpanzees",
      "As a girl she dreamed of living with animals in Africa. In 1960 she went to Gombe, Tanzania, and watched chimpanzees for months. She saw them use grass stems as tools. She spent her life protecting animals and forests.",
      ["chimpanzee|noun", "forest|noun", "patient|adjective", "notebook|noun", "grass|noun"], ["Africa", "termite", "protect"],
      "dream of + -ing", "She dreamed of living with animals in Africa.", ["Nature", "Science", "Women"]),
    E("A2", "Roger Bannister", "1929–2018", "past",
      "Many Said It Was Impossible… Then He Ran a Mile in Under Four Minutes",
      "Many people believed no one could run a mile in less than four minutes. He was a busy medical student who trained in his lunch break. On 6 May 1954 he ran it in 3 minutes 59.4 seconds.",
      ["mile|noun", "record|noun", "minute|noun", "impossible|adjective", "second|noun"], ["stopwatch", "lunch break", "track"],
      "comparatives (faster than, less than)", "He ran faster than anyone before him.", ["Sport", "Health"]),
    E("A2", "Harriet Tubman", "c. 1822–1913", "past",
      "She Escaped Slavery… Then Went Back Again and Again",
      "Born enslaved in Maryland, she escaped to the North in 1849. She was free, but her family was not. She went back about thirteen times and guided around seventy people to freedom, travelling at night.",
      ["escape|verb", "north|noun", "free|adjective", "guide|verb", "night|noun"], ["freedom", "path", "star"],
      "more than / about + number", "She went back about thirteen times.", ["Freedom", "Women", "Courage"]),
    E("A2", "Sadako Sasaki", "1943–1955", "past",
      "She Folded Paper Cranes in Hospital… Then Children Everywhere Folded Them Too",
      "She was two when the bomb fell on Hiroshima. At twelve she became very ill. In hospital she folded paper cranes because of an old Japanese story about wishes. Today a statue of her in Hiroshima asks for peace.",
      ["crane|noun", "fold|verb", "paper|noun", "wish|noun", "peace|noun"], ["statue", "ill", "bird"],
      "so (result)", "She wanted to get better, so she folded cranes every day.", ["Peace", "Childhood", "Asia"]),
    E("A2", "Anne Frank", "1929–1945", "past",
      "She Hid in a Secret Room for Two Years… and Her Diary Speaks to the World",
      "Her family was Jewish and moved from Germany to Amsterdam. In 1942 they hid in secret rooms behind a bookcase. Anne wrote in her diary for two years. Her father published it after the war.",
      ["diary|noun", "hide|verb", "secret|adjective", "hope|noun", "bookcase|noun"], ["Amsterdam", "war", "publish"],
      "for + period of time", "They hid for two years. She wrote for hours every day.", ["History", "Writing", "Childhood"]),
    E("A2", "Louis Armstrong", "1901–1971", "past",
      "He Grew Up Poor in New Orleans… Then His Trumpet Filled the World With Joy",
      "As a boy he sold coal and sang on the street. At a home for boys he learned to play the cornet. He became one of the greatest jazz musicians, and his big smile and warm voice made people happy.",
      ["trumpet|noun", "band|noun", "smile|noun", "jazz|noun", "song|noun"], ["cornet", "coal", "joy"],
      "adverbs of manner (-ly)", "He played beautifully and sang happily.", ["Music", "Childhood"]),
    E("A2", "Bessie Coleman", "1892–1926", "past",
      "No Flight School Would Take Her… So She Learned French and Flew",
      "She worked in Chicago and dreamed of flying. American flight schools did not accept Black women, so she learned French and went to France. In 1921 she became the first African American woman with a pilot's licence.",
      ["licence|noun", "French|noun", "air show|noun", "accept|verb", "save|verb"], ["flight school", "Chicago", "crowd"],
      "decided to + verb", "She decided to learn French.", ["Aviation", "Women", "Equality"]),
    E("A2", "Alexander Fleming", "1881–1955", "past",
      "He Left a Messy Lab for a Holiday… and Came Back to a Medicine That Saved Millions",
      "In 1928 he went on holiday and left some dishes in his lab. When he came back, a mould was growing on one dish, and the germs around it were dead. This mould gave the world penicillin.",
      ["mould|noun", "dish|noun", "holiday|noun", "germ|noun", "medicine|noun"], ["penicillin", "lab", "messy"],
      "past simple + but (contrast)", "The lab was messy, but the mess was lucky.", ["Science", "Health"]),
    E("A2", "Muhammad Ali", "1942–2016", "past",
      "Someone Stole His Bike… Then He Became the Greatest",
      "When he was twelve, his new bike was stolen in Louisville. A police officer who trained boxers told him to learn to fight first. He won Olympic gold in 1960 and became world champion. In 1996 he lit the Olympic flame.",
      ["bike|noun", "steal|verb", "boxing|noun", "champion|noun", "flame|noun"], ["glove", "police officer", "torch"],
      "adverbs of frequency (always, often, never)", "He always trained hard. He never stopped.", ["Sport", "Courage"]),
    E("A2", "Vincent van Gogh", "1853–1890", "past",
      "Few People Bought His Paintings… Now They Are Loved Around the World",
      "He started painting at twenty-seven. His brother Theo helped him and they wrote many letters. In about ten years he made more than two thousand artworks, like Sunflowers and The Starry Night.",
      ["sunflower|noun", "brush|noun", "yellow|adjective", "brother|noun", "artist|noun"], ["starry", "Theo", "canvas"],
      "more and more", "He painted more and more every year.", ["Art"]),
    E("A2", "Wolfgang Amadeus Mozart", "1756–1791", "past",
      "He Wrote Music at Five… and We Still Play It Today",
      "As a small boy in Salzburg he played for kings and queens across Europe. He wrote his first music at about five. In his short life he wrote more than 600 pieces of music.",
      ["composer|noun", "concert|noun", "piece|noun", "king|noun", "travel|verb"], ["Salzburg", "keyboard", "opera"],
      "at the age of + number", "At the age of five, he wrote his first music.", ["Music", "Childhood"]),
    E("A2", "Audrey Hepburn", "1929–1993", "past",
      "She Was Hungry as a Child in the War… Then She Helped Hungry Children Everywhere",
      "She grew up in the Netherlands during World War II and often had little food. After the war, help came from the United Nations. She became a famous actress, and later she travelled the world for UNICEF to help children.",
      ["actress|noun", "dancer|noun", "war|noun", "visit|verb", "kind|adjective"], ["UNICEF", "ballet", "film star"],
      "used to + verb", "She used to be hungry. Later, she used to visit children in many countries.", ["Film", "Kindness", "Women"]),
    E("A2", "Nicholas Winton", "1909–2015", "past",
      "He Saved 669 Children… and Told No One for 50 Years",
      "In 1938 he went to Prague and saw Jewish families in danger. He organised trains to take 669 children to safety in Britain. He never talked about it. In 1988, on a TV show, he met some of the children — now grown up.",
      ["rescue|verb", "list|noun", "scrapbook|noun", "surprise|noun", "safety|noun"], ["Prague", "train", "grown-up"],
      "no one / anyone / everyone", "He didn't tell anyone. No one knew.", ["Kindness", "History"]),
    E("A2", "Isaac Newton", "1643–1727", "past",
      "An Apple Fell From a Tree… and He Asked Why",
      "When the university closed because of a disease, he went home to his mother's farm. Later he said that seeing an apple fall made him think about gravity. He also showed that white light has all the colours of the rainbow.",
      ["apple|noun", "fall|verb", "pull|verb", "rainbow|noun", "planet|noun"], ["gravity", "prism", "tree"],
      "zero conditional (If you…, it…)", "If you drop an apple, it falls.", ["Science", "Curiosity"]),
    E("A2", "Emil Zátopek", "1922–2000", "past",
      "He Ran His First Marathon at the Olympics… and Won",
      "He worked in a shoe factory in Czechoslovakia and didn't like running at first. He trained very hard, even in heavy army boots. At the 1952 Olympics he won the 5,000 m, the 10,000 m and — in his first ever marathon — the marathon.",
      ["marathon|noun", "boot|noun", "train|verb", "heavy|adjective", "army|noun"], ["Olympics", "Czech", "face"],
      "even (for surprise): even in the snow, even in boots", "He trained every day, even in the snow.", ["Sport"]),
    E("A2", "Chiune Sugihara", "1900–1986", "past",
      "He Wrote Visas Day and Night… and Saved Thousands of Lives",
      "In 1940 he was a Japanese diplomat in Lithuania. Many Jewish families came to his office in danger. His government said no, but he wrote travel visas by hand for weeks, until his train left the city.",
      ["visa|noun", "sign|verb", "pen|noun", "office|noun", "government|noun"], ["Lithuania", "diplomat", "stamp"],
      "until", "He wrote visas until his train left.", ["Kindness", "History", "Asia"]),
    E("A2", "Steve Irwin", "1962–2006", "past",
      "He Grew Up in a Zoo… Then Taught the World to Love Wild Animals",
      "His parents started a small zoo in Australia, and he caught his first crocodile as a boy with his dad. On TV he showed people crocodiles and snakes with huge excitement, and he worked to protect wild places.",
      ["zoo|noun", "crocodile|noun", "snake|noun", "wild|adjective", "excited|adjective"], ["Australia", "wildlife", "khaki"],
      "adjectives with -ed and -ing (excited / exciting)", "He was excited. Crocodiles were exciting.", ["Nature", "TV"]),
    E("A2", "Fred Rogers", "1928–2003", "past",
      "He Wore a Sweater and Spoke Softly… and Taught Children About Feelings",
      "He was a shy boy. He saw children's TV and wanted to make something kinder. For more than thirty years, on Mister Rogers' Neighborhood, he changed his shoes, put on a sweater and talked to children about their feelings.",
      ["sweater|noun", "neighbour|noun", "feelings|noun", "listen|verb", "shy|adjective"], ["trainers", "puppet", "television"],
      "it's + adjective + to + verb", "It's okay to feel sad. It's important to listen.", ["TV", "Kindness", "Childhood"]),
    E("A2", "Nick Vujicic", "born 1982", "living",
      "He Was Born Without Arms or Legs… Now He Surfs and Speaks to Millions",
      "Born in Australia without arms or legs, he felt very alone as a boy. He learned to write with his toes, to swim and even to surf. Today he travels the world and tells people never to lose hope.",
      ["arm|noun", "toe|noun", "swim|verb", "surf|verb", "speaker|noun"], ["wave board", "audience", "confident"],
      "learned to + verb", "He learned to write with his toes.", ["Disability", "Courage"]),
    E("A2", "Yuri Gagarin", "1934–1968", "past",
      "A Farm Boy Looked Up at the Planes… Then Became the First Person in Space",
      "He grew up on a farm in Russia and loved planes. He trained as a pilot and was chosen for a secret space programme. On 12 April 1961 he flew around the Earth in 108 minutes and came down by parachute.",
      ["parachute|noun", "capsule|noun", "around|preposition", "choose|verb", "smile|verb"], ["space programme", "Vostok", "farm boy"],
      "prepositions of movement (around, over, down)", "He flew around the Earth and came down by parachute.", ["Space", "Science"]),
    E("A2", "Ruby Bridges", "born 1954", "living",
      "She Was Six… and She Walked Into a School Alone",
      "In 1960 in New Orleans she became the first Black child at an all-white school. Crowds shouted outside, so four US marshals walked with her every day. For most of the year she was the only child in her teacher's class.",
      ["crowd|noun", "classroom|noun", "marshal|noun", "only|adjective", "walk|verb"], ["New Orleans", "first grade", "desk"],
      "the only + noun", "She was the only child in the class.", ["Equality", "Childhood", "Courage"]),
    E("A2", "Charles Schulz", "1922–2000", "past",
      "His Drawings Were Rejected… Then Snoopy Became Famous Everywhere",
      "As a shy boy in Minnesota he loved comics. His school yearbook didn't use his drawings, and Disney didn't give him a job. In 1950 he started Peanuts, with Charlie Brown and Snoopy, and he drew it for fifty years.",
      ["comic|noun", "strip|noun", "character|noun", "beagle|noun", "yearbook|noun"], ["Snoopy", "newspaper", "pencil"],
      "still (continuing): he still drew every day", "He was famous, but he still drew every strip himself.", ["Art", "Comedy"]),
    E("A2", "Levi Strauss", "1829–1902", "past",
      "He Sold Cloth to Gold Miners… and Gave the World Blue Jeans",
      "He moved from Germany to America and opened a shop in San Francisco during the Gold Rush. A tailor, Jacob Davis, used small metal rivets to make work trousers stronger. In 1873 they got a patent — the start of blue jeans.",
      ["jeans|noun", "pocket|noun", "miner|noun", "strong|adjective", "cloth|noun"], ["rivet", "tailor", "Gold Rush"],
      "stronger / better + for + noun", "Rivets made the trousers stronger for miners.", ["Business", "Fashion"]),
    E("A2", "Abebe Bikila", "1932–1973", "past",
      "He Ran a Marathon Barefoot… and Won Olympic Gold",
      "He was a soldier in the Ethiopian Imperial Guard. At the 1960 Rome Olympics his shoes didn't fit, so he ran the marathon barefoot at night and won. He was the first Black African to win Olympic gold.",
      ["barefoot|adjective", "fit|verb", "street|noun", "guard|noun", "finish line|noun"], ["Ethiopia", "Rome", "night race"],
      "without + noun", "He ran without shoes.", ["Sport", "Africa"]),
    E("A2", "Lou Gehrig", "1903–1941", "past",
      "He Played 2,130 Games in a Row… Then Called Himself the Luckiest Man",
      "He was a great baseball player for the New York Yankees and never missed a game for about fourteen years. Then he became very ill with a disease that made him weak. In 1939 he told the crowd he was \"the luckiest man on the face of the earth\".",
      ["lucky|adjective", "speech|noun", "miss|verb", "row|noun", "disease|noun"], ["Yankees", "illness", "stadium crowd"],
      "in a row", "He played 2,130 games in a row.", ["Sport", "Health", "Courage"]),
]
