# Episode plan data: B1 and B2.
from data_a1_a2 import E

B1 = [
    E("B1", "Temple Grandin", "born 1947", "living",
      "Doctors Said She Would Never Talk… Then She Changed How Farms Treat Animals",
      "At two she didn't speak, and doctors suggested sending her away to an institution. Her mother refused and found teachers and speech therapy. Temple thinks in pictures. She became a professor of animal science and designed calmer, kinder systems for cattle.",
      ["autism|noun", "institution|noun", "calm|verb", "cattle|noun", "design|verb"], ["speech therapy", "ranch", "professor"],
      "would + verb for the future in the past (said / thought she would…)", "Doctors said she would never talk.", ["Disability", "Science", "Women"]),
    E("B1", "Ludwig van Beethoven", "1770–1827", "past",
      "He Was Losing His Hearing… Then Wrote His Greatest Symphony",
      "In his late twenties he began to lose his hearing. He was afraid and wrote about it in a private letter, but he kept writing music. At the first performance of his Ninth Symphony in 1824 he was almost completely deaf, and a singer turned him around to see the applause.",
      ["symphony|noun", "orchestra|noun", "applause|noun", "hearing|noun", "performance|noun"], ["Vienna", "conductor", "silence"],
      "although / even though", "Although he couldn't hear the music, he wrote it.", ["Music", "Disability", "Courage"]),
    E("B1", "Stephen Hawking", "1942–2018", "past",
      "Doctors Gave Him Two Years… He Lived Another 55 and Explained the Universe",
      "At 21 he was told he had motor neurone disease. He slowly lost the use of his body, but his mind kept exploring black holes and time. He spoke through a computer voice, and his book A Brief History of Time sold millions of copies.",
      ["universe|noun", "black hole|noun", "diagnose|verb", "copy|noun", "explore|verb"], ["wheelchair", "Cambridge", "computer voice"],
      "be able to (was able to / wasn't able to)", "He wasn't able to walk, but he was able to explore the universe.", ["Science", "Disability"]),
    E("B1", "Charles Darwin", "1809–1882", "past",
      "A Five-Year Voyage and Some Small Birds… Then an Idea That Changed Biology",
      "His father worried he had no direction. In 1831 he joined HMS Beagle on a five-year voyage around the world. On the Galápagos Islands he saw that birds such as finches and mockingbirds were slightly different on each island. Years later his book explained evolution.",
      ["voyage|noun", "species|noun", "beak|noun", "island|noun", "evolution|noun"], ["finch", "Galápagos", "naturalist"],
      "past simple passive (was published, were called)", "His book was published in 1859.", ["Science", "Nature", "Exploration"]),
    E("B1", "Rachel Carson", "1907–1964", "past",
      "She Asked: What If Spring Had No Birds? Then a Book Changed the Law",
      "A marine biologist and writer, she studied how chemical sprays like DDT were harming birds, fish and people. Her 1962 book Silent Spring was so powerful that it helped start the modern environmental movement.",
      ["pesticide|noun", "harm|verb", "chemical|noun", "spray|noun", "environment|noun"], ["DDT", "marine biologist", "bird song"],
      "so … that", "The book was so powerful that it changed the law.", ["Nature", "Science", "Women"]),
    E("B1", "Ernest Shackleton", "1874–1922", "past",
      "His Ship Was Crushed by Ice… Then He Brought Every Man Home",
      "In 1915 his ship Endurance was trapped and crushed by Antarctic ice. For months his men camped on the ice. He sailed a small lifeboat about 1,300 km across a stormy sea to find help — and all 28 men of the Endurance survived.",
      ["crew|noun", "trapped|adjective", "crush|verb", "lifeboat|noun", "storm|noun"], ["Antarctica", "Endurance", "whaling station"],
      "past perfect (had + past participle)", "By the time help came, they had waited for months.", ["Adventure", "Leadership", "Exploration"]),
    E("B1", "Ray Charles", "1930–2004", "past",
      "He Lost His Sight at Seven… Then Invented a New Sound",
      "He grew up poor in the American South and was completely blind by seven. At a school for the blind he learned to read music in braille and play piano. He mixed gospel, blues and jazz into soul music.",
      ["piano|noun", "soul|noun", "blues|noun", "mix|verb", "sight|noun"], ["gospel", "keyboard", "Georgia"],
      "not only … but also", "He not only sang, but also played piano, saxophone and more.", ["Music", "Disability"]),
    E("B1", "Katherine Johnson", "1918–2020", "past",
      "The Astronaut Said: Get the Girl to Check the Numbers",
      "She loved counting as a child and started high school at ten. At NASA she was one of the \"human computers\". In 1962, before John Glenn flew around the Earth, he asked for her to check the computer's calculations.",
      ["calculate|verb", "orbit|noun", "check|verb", "mathematician|noun", "path|noun"], ["NASA", "human computer", "Hidden Figures"],
      "relative clauses with who", "She was the woman who checked the numbers.", ["Science", "Space", "Women"]),
    E("B1", "Kalpana Chawla", "1962–2003", "past",
      "A Girl Who Drew Planes in India… Became an Astronaut",
      "As a girl in Karnal, India, she watched planes and wanted to fly. She studied aerospace engineering in India and the United States. In 1997 she became the first woman born in India to go to space.",
      ["astronaut|noun", "engineering|noun", "dream big|phrase", "shuttle|noun", "mission|noun"], ["India", "Karnal", "space shuttle"],
      "present perfect for experience (Have you ever…?)", "Have you ever looked at the stars and wanted to go there?", ["Space", "Women", "Asia"]),
    E("B1", "Hedy Lamarr", "1914–2000", "past",
      "A Hollywood Star by Day… an Inventor by Night",
      "She was a famous film star, but in her free time she invented things. In the Second World War she and composer George Antheil designed a \"frequency hopping\" system to guide torpedoes. Frequency hopping is still used in some wireless technology today.",
      ["signal|noun", "patent|noun", "frequency|noun", "radio|noun", "star|noun"], ["torpedo", "Hollywood", "Wi-Fi"],
      "be known as / be known for", "She was known as a film star, but today she is also known for her invention.", ["Science", "Women", "Film"]),
    E("B1", "Nikola Tesla", "1856–1943", "past",
      "He Arrived in America With Almost Nothing… and Lit Up Cities",
      "Born in what is now Croatia, he arrived in New York in 1884 with very little money. His ideas about alternating current (AC) helped bring electricity to homes around the world. He imagined machines in his head before building them.",
      ["electricity|noun", "current|noun", "motor|noun", "imagine|verb", "machine|noun"], ["AC", "coil", "New York"],
      "relative clauses with which / that", "He built a motor that used alternating current.", ["Science", "Invention"]),
    E("B1", "George Washington Carver", "c. 1864–1943", "past",
      "Born Into Slavery… He Became the Scientist Who Saved Southern Farms",
      "He was born enslaved in Missouri near the end of the US Civil War. He worked hard to get an education. As a scientist at Tuskegee Institute he taught farmers to grow peanuts and sweet potatoes to make tired soil healthy again.",
      ["peanut|noun", "soil|noun", "crop|noun", "farmer|noun", "healthy|adjective"], ["Tuskegee", "sweet potato", "cotton"],
      "by + -ing (how)", "Farmers made the soil healthy by planting peanuts.", ["Science", "Nature", "Equality"]),
    E("B1", "Johannes Gutenberg", "c. 1400–1468", "past",
      "Books Were Written by Hand… Then One Machine Changed Everything",
      "In the 1400s, books were copied by hand and were very expensive. In Mainz, Germany, he developed a printing press with movable metal letters. His Bible, printed around 1455, showed that many books could be made quickly.",
      ["printing press|noun", "ink|noun", "metal|noun", "page|noun", "expensive|adjective"], ["Bible", "Mainz", "movable type"],
      "present simple passive (books are printed)", "Today, millions of books are printed every year.", ["Invention", "History"]),
    E("B1", "Roberto Clemente", "1934–1972", "past",
      "A Baseball Star Who Gave His Life Helping Others",
      "He grew up in Puerto Rico and became one of baseball's greatest players, with 3,000 hits. He always helped people in need. In 1972 he died in a plane crash while flying supplies to earthquake victims in Nicaragua.",
      ["earthquake|noun", "supplies|noun", "hit|noun", "victim|noun", "generous|adjective"], ["Puerto Rico", "Pittsburgh", "charity"],
      "reported speech (said that…)", "He said that he wanted to help people.", ["Sport", "Kindness"]),
    E("B1", "Clara Barton", "1821–1912", "past",
      "She Was Shy as a Child… Then Ran Toward the Battlefield",
      "She was a shy girl who nursed her brother through a long illness. In the American Civil War she brought supplies and care to wounded soldiers and was called \"the angel of the battlefield\". In 1881 she founded the American Red Cross.",
      ["battlefield|noun", "wounded|adjective", "found|verb", "angel|noun", "volunteer|noun"], ["Red Cross", "Civil War", "bandage"],
      "in order to + verb", "She went to the battlefield in order to help wounded soldiers.", ["Health", "Women", "Kindness"]),
    E("B1", "Jonas Salk", "1914–1995", "past",
      "He Made a Vaccine for Polio… and Didn't Try to Get Rich From It",
      "In the early 1950s, polio frightened families everywhere. Jonas Salk's team developed a vaccine, and in 1955 it was announced safe and effective. When asked who owned the patent, he answered, \"Could you patent the sun?\"",
      ["vaccine|noun", "polio|noun", "effective|adjective", "announce|verb", "own|verb"], ["laboratory", "trial", "injection"],
      "it took + time + to + verb", "It took years to make the vaccine.", ["Health", "Science", "Kindness"]),
    E("B1", "Srinivasa Ramanujan", "1887–1920", "past",
      "A Clerk in India Wrote a Letter… and a Famous Mathematician Wrote Back",
      "He taught himself mathematics from a book and filled notebooks with formulas. Working as a clerk in Madras, he wrote to G. H. Hardy at Cambridge in 1913. Hardy invited him to England, where he did amazing work before dying young.",
      ["formula|noun", "genius|noun", "clerk|noun", "theory|noun", "invite|verb"], ["Madras", "Cambridge", "infinity"],
      "taught himself / herself (reflexive pronouns)", "He taught himself mathematics.", ["Science", "Asia", "Education"]),
    E("B1", "Mary Seacole", "1805–1881", "past",
      "They Said No to Her… So She Went to the War Anyway",
      "A Jamaican nurse with knowledge of herbal medicine, she asked to join the nurses going to the Crimean War and was refused. She paid for her own journey and opened the British Hotel near the front, where she cared for soldiers.",
      ["herb|noun", "cure|verb", "journey|noun", "hotel|noun", "knowledge|noun"], ["Jamaica", "Crimea", "remedy"],
      "managed to + verb", "She managed to reach the front on her own.", ["Health", "Women", "Courage"]),
    E("B1", "Soichiro Honda", "1906–1991", "past",
      "He Failed Again and Again… Then Built One of the World's Biggest Car Companies",
      "His first piston rings were rejected. His factory was damaged in the war and by an earthquake. He began again, put small engines on bicycles, and built Honda into a famous company. He said success is built on failure.",
      ["engine|noun", "motorcycle|noun", "failure|noun", "reject|verb", "success|noun"], ["piston ring", "bicycle", "workshop"],
      "learn from your mistakes (set expression)", "He learned from his mistakes and tried again.", ["Business", "Invention", "Asia"]),
    E("B1", "Rosalind Franklin", "1920–1958", "past",
      "Her X-Ray Photo Showed the Secret of Life",
      "She was a brilliant scientist who used X-rays to study tiny structures. Her famous Photo 51 helped show that DNA has a double-helix shape. Her part in the discovery was not fully recognised in her lifetime.",
      ["X-ray|noun", "DNA|noun", "photograph|noun", "shape|noun", "recognise|verb"], ["double helix", "crystal", "King's College"],
      "relative clauses with whose", "She was the scientist whose photo showed the shape of DNA.", ["Science", "Women"]),
    E("B1", "Maya Angelou", "1928–2014", "past",
      "She Didn't Speak for Five Years… Then Her Voice Reached the World",
      "After a painful experience as a young girl, she stopped speaking for almost five years. A neighbour gave her books and poems to read aloud. She became a poet, writer and teacher, and her book I Know Why the Caged Bird Sings was read everywhere.",
      ["poem|noun", "poet|noun", "aloud|adverb", "cage|noun", "library|noun"], ["memoir", "neighbour", "stage"],
      "stop + -ing / start + -ing", "She stopped speaking. Years later, she started writing poems.", ["Writing", "Women", "Courage"]),
    E("B1", "Charles Dickens", "1812–1870", "past",
      "At Twelve He Worked in a Factory… Then Wrote for the Poor Children of London",
      "When his father was sent to prison for debt, 12-year-old Charles had to work in a factory, sticking labels on pots of shoe polish. He never forgot it. His novels, like Oliver Twist, showed people how hard life was for poor children.",
      ["debt|noun", "prison|noun", "novel|noun", "label|noun", "orphan|noun"], ["London", "shoe polish", "Oliver Twist"],
      "make + someone + verb (causative make)", "His novels made people think about poor children.", ["Writing", "Childhood"]),
    E("B1", "Gertrude Ederle", "1905–2003", "past",
      "People Said Women Were Too Weak… She Swam the English Channel",
      "She learned to swim as a child and won Olympic medals in 1924. In 1926 she swam from France to England through cold water and strong tides. She was the first woman to swim the Channel — and faster than any man before her.",
      ["channel|noun", "tide|noun", "swimmer|noun", "goggles|noun", "cross|verb"], ["English Channel", "grease", "boat"],
      "too … to (People said she was too weak to swim it)", "People said women were too weak to swim the Channel.", ["Sport", "Women"]),
    E("B1", "Grace Hopper", "1906–1992", "past",
      "She Found a Real Bug in a Computer… and Taught Computers to Understand English",
      "A mathematician and US Navy officer, she worked on early computers. In 1947 her team found a moth stuck in a machine and taped it in their logbook. She believed computers should use words, not only numbers, and helped create the COBOL language.",
      ["bug|noun", "moth|noun", "program|noun", "code|noun", "language|noun"], ["logbook", "navy", "COBOL"],
      "should (advice / opinion)", "She believed computers should understand words.", ["Science", "Women", "Technology"]),
    E("B1", "Anne Sullivan", "1866–1936", "past",
      "She Grew Up in a Poorhouse, Nearly Blind… Then Became the Teacher Who Opened Helen Keller's World",
      "As a child she lost her mother and was sent to a poorhouse. She begged to go to school and at fourteen entered the Perkins School for the Blind, where eye operations helped her see better. At twenty she went to teach six-year-old Helen Keller.",
      ["poorhouse|noun", "operation|noun", "beg|verb", "graduate|verb", "patience|noun"], ["Perkins School", "finger spelling", "valedictorian"],
      "past perfect with before / by the time", "By the time she met Helen, she had learned finger spelling.", ["Education", "Disability", "Women"]),
    E("B1", "Irena Sendler", "1910–2008", "past",
      "She Hid Children's Names in Jars Under a Tree",
      "A social worker in Warsaw during the Second World War, she helped smuggle Jewish children out of the ghetto to safety. She wrote their real names on paper and buried the lists in jars so their families could find them later.",
      ["jar|noun", "bury|verb", "smuggle|verb", "social worker|noun", "identity|noun"], ["Warsaw", "ghetto", "apple tree"],
      "so that (purpose)", "She buried the names so that the children could find their families.", ["Kindness", "History", "Women"]),
    E("B1", "Jacques Cousteau", "1910–1997", "past",
      "He Wanted to Breathe Underwater… So He Helped Invent a Way",
      "After a car accident, he began swimming in the sea to get stronger and fell in love with the underwater world. In 1943 he and engineer Émile Gagnan developed the Aqua-Lung. His films showed millions of people the life of the oceans.",
      ["dive|verb", "underwater|adverb", "breathe|verb", "tank|noun", "coral|noun"], ["Aqua-Lung", "Calypso", "documentary"],
      "for the first time", "For the first time, people could breathe underwater for a long time.", ["Nature", "Invention", "Adventure"]),
    E("B1", "Ludwig Guttmann", "1899–1980", "past",
      "Doctors Gave Up on Patients With Spinal Injuries… He Gave Them Sport",
      "A Jewish doctor who fled Nazi Germany, he worked at Stoke Mandeville Hospital in England. He believed sport could help people with spinal injuries live full lives. On the opening day of the 1948 London Olympics he held games for wheelchair athletes — the start of the Paralympics.",
      ["spinal injury|noun", "wheelchair|noun", "patient|noun", "games|noun", "flee|verb"], ["Paralympics", "Stoke Mandeville", "archery"],
      "believe (that) + clause", "He believed that sport could change lives.", ["Sport", "Health", "Disability"]),
]

B2 = [
    E("B2", "Fridtjof Nansen", "1861–1930", "past",
      "He Skied Across Greenland… Then Gave Refugees a Passport",
      "An explorer and scientist, he crossed the Greenland ice cap on skis in 1888 and drifted toward the North Pole in his ship Fram. After the First World War he led efforts to bring prisoners of war home and created the \"Nansen passport\" for stateless refugees, winning the Nobel Peace Prize in 1922.",
      ["refugee|noun", "stateless|adjective", "drift|verb", "expedition|noun", "humanitarian|adjective"], ["Greenland", "Fram", "Nansen passport"],
      "inversion: Not only did he …, but he also …", "Not only did he cross Greenland, but he also helped hundreds of thousands of prisoners return home.", ["Exploration", "Kindness"]),
    E("B2", "Alan Turing", "1912–1954", "past",
      "He Helped Break a Secret Code… and Imagined the Computer",
      "At Bletchley Park in the Second World War, he helped design machines to break Germany's Enigma code. Historians believe this shortened the war. He also imagined a universal computing machine and asked whether machines could think. He was treated unjustly by the laws of his time and was pardoned in 2013.",
      ["codebreaker|noun", "decipher|verb", "universal|adjective", "pardon|noun", "unjust|adjective"], ["Enigma", "Bletchley Park", "Turing test"],
      "third conditional (If … had …, … would/might have …)", "If the code hadn't been broken, the war might have lasted longer.", ["Science", "Technology", "History"]),
    E("B2", "Ada Lovelace", "1815–1852", "past",
      "She Saw the Future of Computers… 100 Years Early",
      "Daughter of the poet Lord Byron, she was taught mathematics from a young age. Working with Charles Babbage on his Analytical Engine, she wrote notes in 1843 that included what many call the first computer program — and she imagined machines making music.",
      ["algorithm|noun", "analytical|adjective", "visionary|noun", "notes|noun", "calculation|noun"], ["Analytical Engine", "Babbage", "Byron"],
      "ahead of her time (set expression)", "Her ideas were a hundred years ahead of her time.", ["Science", "Women", "Technology"]),
    E("B2", "Marie Curie", "1867–1934", "past",
      "She Drove X-Ray Cars to the Front Line in the First World War",
      "When war broke out in 1914, she realised that X-rays could help surgeons find bullets. She learned to drive, equipped vehicles with X-ray machines — soldiers called them \"little Curies\" — and trained about 150 women to operate them.",
      ["surgeon|noun", "equip|verb", "front line|noun", "vehicle|noun", "operate|verb"], ["petites Curies", "radiology", "bullet"],
      "participle clauses (Realising …, she …)", "Realising that X-rays could save lives, she learned to drive.", ["Science", "Women", "History"]),
    E("B2", "Nellie Bly", "1864–1922", "past",
      "She Pretended to Be Ill to Expose an Asylum… Then Raced Around the World",
      "In 1887 the young reporter got herself admitted to an asylum in New York to report on the terrible conditions inside; her articles led to reforms. In 1889–90 she travelled around the world in 72 days, beating the fictional record of Around the World in Eighty Days.",
      ["reporter|noun", "expose|verb", "asylum|noun", "reform|noun", "undercover|adjective"], ["New York World", "Jules Verne", "72 days"],
      "reporting verbs (claimed, insisted, promised)", "She insisted on going alone and promised to beat the record.", ["Writing", "Women", "Adventure"]),
    E("B2", "Frederick Douglass", "c. 1818–1895", "past",
      "He Was Forbidden to Read… So He Taught Himself and Changed a Nation's Mind",
      "Born enslaved in Maryland, he learned the alphabet as a boy and secretly taught himself to read. He escaped in 1838, and his autobiography and powerful speeches made him one of the most important voices against slavery.",
      ["forbid|verb", "autobiography|noun", "abolish|verb", "eloquent|adjective", "literacy|noun"], ["Maryland", "newspaper", "The North Star"],
      "cleft sentences (It was … that …)", "It was reading that showed him the way to freedom.", ["Freedom", "Writing", "Education"]),
    E("B2", "Edward Jenner", "1749–1823", "past",
      "A Milkmaid's Story Led to the World's First Vaccine",
      "Country people said that milkmaids who caught cowpox didn't get smallpox. In 1796 the doctor tested this idea on eight-year-old James Phipps. His work led to vaccination, and smallpox was declared eradicated in 1980.",
      ["smallpox|noun", "immune|adjective", "eradicate|verb", "milkmaid|noun", "contagious|adjective"], ["cowpox", "James Phipps", "vaccination"],
      "passive reporting (It was said that … / were thought to …)", "Milkmaids were thought to be immune to smallpox.", ["Health", "Science"]),
    E("B2", "Louis Pasteur", "1822–1895", "past",
      "A Boy Was Bitten by a Rabid Dog… and Pasteur Took a Huge Risk",
      "He showed that tiny microbes cause disease and invented pasteurisation to make milk safe. In 1885 nine-year-old Joseph Meister was bitten by a rabid dog; Pasteur's experimental vaccine saved him.",
      ["microbe|noun", "rabies|noun", "experimental|adjective", "take a risk|phrase", "pasteurise|verb"], ["Joseph Meister", "laboratory", "milk"],
      "had no choice but to + verb", "He had no choice but to try the new vaccine.", ["Science", "Health"]),
    E("B2", "Zheng He", "1371–1433", "past",
      "He Led Huge Fleets Across the Indian Ocean… Decades Before Columbus",
      "Between 1405 and 1433, the Ming admiral led seven great voyages across the Indian Ocean, reaching Southeast Asia, India, Arabia and East Africa with fleets of large ships and tens of thousands of sailors.",
      ["fleet|noun", "admiral|noun", "treasure|noun", "diplomacy|noun", "vast|adjective"], ["Ming dynasty", "treasure ship", "giraffe"],
      "such + (a) + adjective + noun + that", "It was such a vast fleet that people could not believe their eyes.", ["Exploration", "Asia", "History"]),
    E("B2", "Ibn Battuta", "1304–c. 1369", "past",
      "He Left Home for a Pilgrimage… and Travelled for 29 Years",
      "At 21 he left Tangier in Morocco. His journeys took him across North Africa, the Middle East, India, China and West Africa — tens of thousands of kilometres. Back home, he told his story, which was written down as the Rihla.",
      ["pilgrimage|noun", "caravan|noun", "wander|verb", "chronicle|noun", "hospitality|noun"], ["Tangier", "Rihla", "Silk Road"],
      "would for past habits", "He would stay in a city for months before moving on.", ["Exploration", "Africa", "Asia"]),
    E("B2", "Mary Shelley", "1797–1851", "past",
      "A Ghost Story Contest on a Stormy Night… Created Frankenstein",
      "In 1816, stuck indoors by bad weather near Lake Geneva, friends challenged each other to write ghost stories. The 18-year-old Mary imagined a scientist who creates life. Frankenstein, published in 1818, is often called the first science fiction novel.",
      ["challenge|verb", "ghost|noun", "creature|noun", "science fiction|noun", "gothic|adjective"], ["Lake Geneva", "Frankenstein", "villa"],
      "no sooner … than / hardly … when", "No sooner had the challenge begun than she started to imagine her monster.", ["Writing", "Women"]),
    E("B2", "Leonardo da Vinci", "1452–1519", "past",
      "He Painted the Mona Lisa… and Designed Flying Machines 400 Years Early",
      "An artist, engineer and scientist, he filled thousands of notebook pages with mirror writing, studies of the human body, and designs for flying machines and bridges. He painted the Mona Lisa and The Last Supper.",
      ["sketch|noun", "anatomy|noun", "curiosity|noun", "mirror writing|noun", "masterpiece|noun"], ["Mona Lisa", "Florence", "flying machine"],
      "modal perfect: must have / might have", "He must have spent thousands of hours on his notebooks.", ["Art", "Science", "Curiosity"]),
    E("B2", "Arthur Ashe", "1943–1993", "past",
      "He Was Kept Out of Tennis Clubs… Then Won Wimbledon",
      "Growing up in segregated Richmond, Virginia, he was not allowed on many courts. In 1975 he became the first Black man to win Wimbledon. After getting HIV from a blood transfusion, he spent his last years fighting for education and awareness.",
      ["segregated|adjective", "court|noun", "transfusion|noun", "awareness|noun", "dignity|noun"], ["Wimbledon", "Richmond", "racket"],
      "imperatives for advice: Start where you are. Use what you have.", "\"Start where you are. Use what you have. Do what you can.\"", ["Sport", "Equality", "Health"]),
    E("B2", "Althea Gibson", "1927–2003", "past",
      "She Learned Tennis in the Streets of Harlem… Then Won Wimbledon",
      "She played paddle tennis on a closed-off street in Harlem. Despite segregation, she broke the colour barrier in international tennis and in 1957 became the first Black player to win Wimbledon.",
      ["barrier|noun", "despite|preposition", "tournament|noun", "determination|noun", "paddle|noun"], ["Harlem", "Wimbledon", "US Open"],
      "despite / in spite of + noun / -ing", "Despite segregation, she became a champion.", ["Sport", "Women", "Equality"]),
    E("B2", "Christopher Reeve", "1952–2004", "past",
      "He Played Superman… Then Showed a Different Kind of Strength",
      "After a riding accident in 1995 left him paralysed from the neck down, the actor became a powerful campaigner for spinal cord research and for people living with paralysis.",
      ["paralysed|adjective", "campaigner|noun", "research|noun", "spinal cord|noun", "strength|noun"], ["Superman", "foundation", "horse riding"],
      "be used to + -ing vs used to + verb", "He used to fly as Superman. He wasn't used to depending on others.", ["Film", "Disability", "Health"]),
    E("B2", "J. R. R. Tolkien", "1892–1973", "past",
      "He Invented Languages for Fun… Then Built a Whole World",
      "An orphan by twelve and a soldier in the First World War, he became an Oxford professor who loved old languages. He invented languages and then created Middle-earth, the world of The Hobbit and The Lord of the Rings.",
      ["linguist|noun", "myth|noun", "trilogy|noun", "trench|noun", "imaginary|adjective"], ["Middle-earth", "Oxford", "hobbit"],
      "the more …, the more …", "The more languages he invented, the more his world grew.", ["Writing", "Imagination"]),
    E("B2", "Satyajit Ray", "1921–1992", "past",
      "He Had Almost No Money for His First Film… Then Won an Honorary Oscar",
      "Working in advertising in Calcutta, he spent years making his first film, Pather Panchali, with a small crew and little money. It was released in 1955 and praised worldwide. In 1992 he received an honorary Oscar.",
      ["director|noun", "budget|noun", "release|verb", "acclaim|noun", "screenplay|noun"], ["Calcutta", "Pather Panchali", "honorary Oscar"],
      "however / no matter how", "No matter how little money he had, he kept filming.", ["Film", "Art", "Asia"]),
    E("B2", "Tu Youyou", "born 1930", "living",
      "An Ancient Text Held the Clue… and Her Discovery Has Saved Millions From Malaria",
      "In the 1960s and 70s her team searched old Chinese medical texts for a malaria treatment. A 1,600-year-old text gave a clue about sweet wormwood. Her team extracted artemisinin, and she volunteered to test it herself. In 2015 she won a Nobel Prize.",
      ["malaria|noun", "extract|verb", "ancient|adjective", "treatment|noun", "volunteer|verb"], ["artemisinin", "sweet wormwood", "Nobel Prize"],
      "present perfect passive (has been used / have been saved)", "Artemisinin has been used to treat millions of people.", ["Health", "Science", "Women", "Asia"]),
    E("B2", "Joseph Lister", "1827–1912", "past",
      "Many Patients Died After Surgery… Until He Made Hospitals Clean",
      "Inspired by Pasteur's germ theory, the surgeon began using carbolic acid to clean wounds and instruments in 1867. Deaths from infection after operations fell sharply, and antiseptic surgery spread around the world.",
      ["infection|noun", "antiseptic|adjective", "wound|noun", "instrument|noun", "sterile|adjective"], ["carbolic acid", "germ theory", "Glasgow"],
      "it wasn't until … that …", "It wasn't until Lister that surgeons cleaned their hands and tools.", ["Health", "Science"]),
    E("B2", "Albert Einstein", "1879–1955", "past",
      "A Patent Clerk's Miracle Year Changed Physics Forever",
      "Unable to get a university job, he worked as a clerk at the patent office in Bern. In 1905, in his spare time, he published four papers — including special relativity and E = mc² — that transformed physics.",
      ["relativity|noun", "patent office|noun", "transform|verb", "spare time|noun", "breakthrough|noun"], ["Bern", "E = mc²", "miracle year"],
      "reduced relative clauses (papers written in his spare time)", "Four papers written in his spare time changed physics.", ["Science", "Curiosity"]),
]
