# Final lesson-extra words (real vocabulary, no place names) and a few video-word fixes.
EXTRAS = {
 ("Louis Braille","A1"): ["tool","alphabet","raised"],
 ("Hans Christian Andersen","A1"): ["fairy tale","shoemaker","swan"],
 ("Momofuku Ando","A1"): ["shed","line","soup"],
 ("Jesse Owens","A1"): ["stadium","athlete","friend"],
 ("Amelia Earhart","A1"): ["pilot","fair","flight"],
 ("Beatrix Potter","A1"): ["picture","lake","sheep"],
 ("Pelé","A1"): ["field","shirt","score"],
 ("Charlie Chaplin","A1"): ["walking stick","actor","moustache"],
 ("Walt Disney","A1"): ["drawing","magic","studio"],
 ("Neil Armstrong","A1"): ["flag","helmet","footprint"],
 ("Thomas Edison","A1"): ["lab","idea","electric"],
 ("Florence Nightingale","A1"): ["bed","care","dirty"],
 ("Jackie Robinson","A1"): ["fan","uniform","angry"],
 ("Rosa Parks","A1"): ["law","tired","quiet"],
 ("Roald Amundsen","A1"): ["ski","explorer","south"],
 ("Mary Anning","A1"): ["fossil","museum","hammer"],
 ("Katsushika Hokusai","A1"): ["print","fisherman","wood"],
 ("Albert Einstein","A1"): ["needle","science","math"],
 ("Jim Henson","A1"): ["ping-pong ball","show","voice"],
 ("Milton Hershey","A1"): ["caramel","worker","shop"],
 ("Marie Curie","A2"): ["physics","chemistry","husband"],
 ("Frida Kahlo","A2"): ["self-portrait","flower","pain"],
 ("Tenzing Norgay","A2"): ["camp","porter","peak"],
 ("Jane Goodall","A2"): ["termite","protect","degree"],
 ("Roger Bannister","A2"): ["stopwatch","lunch break","track"],
 ("Harriet Tubman","A2"): ["freedom","enslaved","danger"],
 ("Sadako Sasaki","A2"): ["statue","ill","bird"],
 ("Anne Frank","A2"): ["publish","birthday","father"],
 ("Louis Armstrong","A2"): ["cornet","coal","joy"],
 ("Bessie Coleman","A2"): ["flight school","dangerous","trick"],
 ("Alexander Fleming","A2"): ["penicillin","messy","bacteria"],
 ("Muhammad Ali","A2"): ["glove","police officer","torch"],
 ("Vincent van Gogh","A2"): ["starry","canvas","sell"],
 ("Wolfgang Amadeus Mozart","A2"): ["opera","queen","note"],
 ("Audrey Hepburn","A2"): ["ballet","film star","hunger"],
 ("Nicholas Winton","A2"): ["grown-up","platform","foster family"],
 ("Isaac Newton","A2"): ["gravity","prism","tree"],
 ("Emil Zátopek","A2"): ["lap","sweat","record-breaker"],
 ("Chiune Sugihara","A2"): ["diplomat","stamp","handwriting"],
 ("Steve Irwin","A2"): ["wildlife","khaki","reptile"],
 ("Fred Rogers","A2"): ["trainers","zip","kindness"],
 ("Nick Vujicic","A2"): ["audience","confident","skateboard"],
 ("Yuri Gagarin","A2"): ["cosmonaut","space programme","hometown"],
 ("Ruby Bridges","A2"): ["first grade","desk","escort"],
 ("Charles Schulz","A2"): ["pencil","cartoonist","joke"],
 ("Levi Strauss","A2"): ["rivet","tailor","trousers"],
 ("Abebe Bikila","A2"): ["night race","pace","national team"],
 ("Lou Gehrig","A2"): ["illness","streak","retire"],
 ("Temple Grandin","B1"): ["speech therapy","ranch","professor"],
 ("Ludwig van Beethoven","B1"): ["conductor","silence","premiere"],
 ("Stephen Hawking","B1"): ["computer voice","bestseller","lecture"],
 ("Charles Darwin","B1"): ["finch","naturalist","tortoise"],
 ("Rachel Carson","B1"): ["marine biologist","bird song","insect"],
 ("Ernest Shackleton","B1"): ["whaling station","penguin","captain"],
 ("Ray Charles","B1"): ["gospel","keyboard","braille"],
 ("Katherine Johnson","B1"): ["human computer","launch","trajectory"],
 ("Kalpana Chawla","B1"): ["space shuttle","aerospace","village"],
 ("Hedy Lamarr","B1"): ["torpedo","inventor","wireless"],
 ("Nikola Tesla","B1"): ["coil","alternating current","lightning"],
 ("George Washington Carver","B1"): ["sweet potato","cotton","nutrient"],
 ("Johannes Gutenberg","B1"): ["movable type","scribe","printer"],
 ("Roberto Clemente","B1"): ["charity","relief","humble"],
 ("Clara Barton","B1"): ["bandage","nursing","disaster"],
 ("Jonas Salk","B1"): ["laboratory","trial","injection"],
 ("Srinivasa Ramanujan","B1"): ["infinity","prime number","scholarship"],
 ("Mary Seacole","B1"): ["remedy","cholera","fever"],
 ("Soichiro Honda","B1"): ["piston ring","bicycle","workshop"],
 ("Rosalind Franklin","B1"): ["double helix","crystal","molecule"],
 ("Maya Angelou","B1"): ["memoir","stage","poetry"],
 ("Charles Dickens","B1"): ["shoe polish","workhouse","serial"],
 ("Gertrude Ederle","B1"): ["grease","boat","jellyfish"],
 ("Grace Hopper","B1"): ["logbook","navy","compiler"],
 ("Anne Sullivan","B1"): ["finger spelling","valedictorian","eyesight"],
 ("Irena Sendler","B1"): ["ghetto","apple tree","rescuer"],
 ("Jacques Cousteau","B1"): ["documentary","fin","scuba"],
 ("Ludwig Guttmann","B1"): ["archery","disability","rehabilitation"],
 ("Fridtjof Nansen","B2"): ["ice cap","prisoner of war","peace prize"],
 ("Alan Turing","B2"): ["codebreaking","wartime","persecution"],
 ("Ada Lovelace","B2"): ["mathematics","punch card","countess"],
 ("Marie Curie","B2"): ["radiology","bullet","ambulance"],
 ("Nellie Bly","B2"): ["journalist","conditions","circumnavigate"],
 ("Frederick Douglass","B2"): ["newspaper","abolitionist","conscience"],
 ("Edward Jenner","B2"): ["cowpox","vaccination","scar"],
 ("Louis Pasteur","B2"): ["bite","spoil","fermentation"],
 ("Zheng He","B2"): ["treasure ship","giraffe","envoy"],
 ("Ibn Battuta","B2"): ["travel writer","scholar","homesick"],
 ("Mary Shelley","B2"): ["villa","monster","novelist"],
 ("Leonardo da Vinci","B2"): ["flying machine","apprentice","polymath"],
 ("Arthur Ashe","B2"): ["racket","grand slam","activist"],
 ("Althea Gibson","B2"): ["trophy","pioneer","amateur"],
 ("Christopher Reeve","B2"): ["foundation","horse riding","advocate"],
 ("J. R. R. Tolkien","B2"): ["hobbit","elvish","manuscript"],
 ("Satyajit Ray","B2"): ["honorary award","advertising","jewellery"],
 ("Tu Youyou","B2"): ["artemisinin","sweet wormwood","clinical trial"],
 ("Joseph Lister","B2"): ["carbolic acid","germ theory","operating theatre"],
 ("Albert Einstein","B2"): ["miracle year","physicist","photon"],
}
WORD_FIX = {  # (person, level): {old word: new "word|pos"}
 ("Tenzing Norgay","A2"): {"guide": "carry|verb"},
 ("Yuri Gagarin","A2"): {"smile": "land|verb"},
 ("Ludwig Guttmann","B1"): {"patient": "compete|verb"},
 ("Tu Youyou","B2"): {"volunteer": "dose|noun"},
}
def apply(ALL):
    for e in ALL:
        k = (e['person'], e['level'])
        e['extras'] = EXTRAS[k]
        for old, new in WORD_FIX.get(k, {}).items():
            e['words'] = [new if w.split('|')[0] == old else w for w in e['words']]
    return ALL
